const mongoose = require('mongoose');
mongoose.connect('mongodb://127.0.0.1/Autoconnectxs', { useNewUrlParser: true });

const Schema = mongoose.Schema;

const pecaSchema = new Schema({
  nome: { type: String, required: true },
  tipoDePeca: {
    type: String,
    required: true,
    enum: [
      'Motor',
      'Cabeçote',
      'Bloco do motor',
      'Bielas',
      'Rodas',
      'Pistões',
      'Anéis de pistão',
      'Virabrequim',
      'Comando de válvulas',
      'Válvulas',
      'Tuchos',
      'Correia dentada',
      'Corrente de distribuição',
      'Bomba de óleo',
      'Bomba de água',
      'Bomba de combustível',
      'Radiador de óleo',
      'Filtro de ar',
      'Filtro de óleo',
      'Filtro de combustível',
      'Velas de ignição',
      'Cabos de ignição',
      'Sistema de injeção de combustível',
      'Sistema de ignição',
      'Disco de embreagem',
      'Platô de embreagem',
      'Rolamento de embreagem',
      'Cilindro mestre de embreagem',
      'Cilindro escravo de embreagem',
      'Tanque de combustível',
      'Bomba de combustível',
      'Bóia de nível de combustível',
      'Catalisador',
      'Tubo de escape',
      'Silenciador',
      'Molas de suspensão',
      'Molas helicoidais',
      'Molas a ar',
      'Discos de freio dianteiros',
      'Discos de freio traseiros',
      'Pastilhas de freio',
      'Pinças de freio',
      'Cilindro mestre de freio',
      'Cilindros de roda',
      'Radiador',
      'Ventoinha do radiador',
      'Mangueiras de radiador',
      'Válvula termostática',
      'Portas',
      'Capô',
      'Para-lamas',
      'Para-choques',
      'Teto',
      'Vidros',
      'Retrovisores',
      'Lanternas',
      'Faróis',
      'Grades',
      'Painel de instrumentos',
      'Bancos',
      'Tapetes',
      'Volante',
      'Cintos de segurança',
      'Airbags'
    ],
    required: true,
  },
  marca: {
    type: String,
    required: true,
    enum: [
      'Chevrolet',
      'Volkswagen',
      'Fiat',
      'Ford',
      'Toyota',
      'Honda',
      'Renault',
      'Hyundai',
      'Nissan',
      'Jeep'
    ]
  },
  modelo: { type: String, required: true },
  ano: { type: Number, required: true },
  descricao: { type: String, required: true },
  preco: { type: Number, required: true },
  qtdEstoque: { type: Number, required: true, min: 0 },
  status: {
    type: String,
    enum: ['Disponivel', 'Vendida', 'Manutenção'],
    required: true,
  },
  idVendedor: {
    type: Schema.Types.ObjectId,
    ref: 'Vendedor',
    required: true,
  },
  partesVeiculo: {
    type: [String],
    enum: [
      'Motor e Componentes',
      'Embreagem',
      'Tanque de combustível',
      'Catalisador',
      'Rodas',
      'Disco de freio',
      'Radiador',
      'carroceria',
    ],
    required: true,
  },
});

const Peca = mongoose.model('Peca', pecaSchema);

module.exports = Peca;
